FROM ubuntu:16.04

EXPOSE 5000
ENV API_URL=http://localhost:8000

WORKDIR /workspace
COPY . /workspace

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/* && \
    npm install && \
    useradd -m frontend && \
    chown -R frontend:frontend $(pwd)

USER frontend

CMD [ "npm", "start" ]
